### ISSUE TITLE
Add step for linux for SECRET_KEY

### ISSUE THREAD

**Issue by berziiii** [ga-wdi-boston/express-api#20]
`sudo echo SECRET_KEY=$(/usr/local/opt/openssl/bin/openssl rand -base64 66 | tr -d '\n') >>.env` 

?? Total guess...

**Comment by raq929** [comment]
@gaand, do you know the linux command to do this?

**Comment by gaand** [comment]
```sh
echo SECRET_KEY=$(/usr/bin/openssl rand -base64 66 | tr -d '\n') >>.env
```
