### ISSUE TITLE
Order: GET GET DELETE PATCH POST

### ISSUE THREAD

**Issue by raq929** [ga-wdi-boston/express-api#31]
For creating methods. 
This is inline with how we are teaching rails, and pedagogically what we want.

**Comment by raq929** [comment]
This requires seed data in the database and another install step for them to seed the data.

**Comment by gaand** [comment]
I think loading example data happens JIT.  So, after `GET /books` (or whatever) returns `[]`, then have the developers run a script to load the examples.

Note:  This is not `seed` data.
