### ISSUE TITLE
Typo in bash command

### ISSUE THREAD

**Issue by raq929** [ga-wdi-boston/express-api#41]
```diff
- ```sh
+ ```bash
    echo SECRET_KEY=$(/usr/local/opt/openssl/bin/openssl rand -base64 66 | tr -d '\n') >>.env
    ```
```

**Comment by gaand** [comment]
Why is this change necessary?  Does it change the highlighting or otherwise improve the code block?

Also, your diff isn't consistently formatted 🤖  😈

**Comment by raq929** [comment]
It currently prints the `sh`, which people then copy and wonder why it doesn't work. This is a duplicate of #35 anyway.
